### ISSUE TITLE
"dotnet run" error after modify "config.json"

### ISSUE THREAD

**Issue by mingtong** [shadowsocks/Shadowsocks-Net#3]
After I modify the "config.json", it report this error when I do "dotnet run".
OS: CentOS 8.
donet version: 3.1.101

Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Byte. Path: $.timeout | LineNumber: 4 | BytePositionInLine: 17.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an unsigned byte.
   at System.Text.Json.Utf8JsonReader.GetByte() in /_/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.TryGet.cs:line 135
   at System.Text.Json.Serialization.Converters.JsonConverterByte.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterByte.cs:line 11
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoNotNullable.cs:line 25
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfo.cs:line 457
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.cs:line 50
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex) in /_/src/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 161
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.cs:line 128
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 19
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 89
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 31
   at Shadowsocks_Minimal_Crossplatform_Remote.Program.Main(String[] args) in /root/Shadowsocks-Net/Shadowsocks-Net/Minimal/Shadowsocks-Minimal-CrossPlatform-Remote/Program.cs:line 61
   at Shadowsocks_Minimal_Crossplatform_Remote.Program.<Main>(String[] args)

**Comment by ohsorry** [comment]
`timout` is a `Byte` value currently. try a smaller value between 0-255.
